"""Knowledge Brain Observer Configuration

Thresholds and configuration for monitoring and alerting.
"""

# Stability Alert Thresholds
THRESHOLD_PENDING_REVIEW_CRITICAL = 5
THRESHOLD_PENDING_REVIEW_WARNING = 3

THRESHOLD_SIM_APPROVE_RATE_CRITICAL = 0.5
THRESHOLD_SIM_APPROVE_RATE_WARNING = 0.7

THRESHOLD_STRATEGY_DEGRADATION_CRITICAL = 2
THRESHOLD_STRATEGY_DEGRADATION_WARNING = 1

# Time Windows
DAYS_FOR_SECTIONS_MODIFIED = 7
DAYS_FOR_SIMULATIONS = 30
HOURS_FOR_S_RANK_RECALCULATIONS = 24
DAYS_FOR_STRATEGY_DEGRADATION = 7

